# Generated by Django 5.0.6 on 2024-06-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_url_full', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
